//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domotica_ASP {
    
    
    public partial class index {
        
        /// <summary>
        /// grid_parent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grid_parent;
        
        /// <summary>
        /// Widget1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget1;
        
        /// <summary>
        /// Vertical control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Vertical;
        
        /// <summary>
        /// Widget2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget2;
        
        /// <summary>
        /// Horizontal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Horizontal;
        
        /// <summary>
        /// Widget3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget3;
        
        /// <summary>
        /// Number control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Number;
        
        /// <summary>
        /// Widget4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget4;
        
        /// <summary>
        /// Text control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Text;
        
        /// <summary>
        /// Widget5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget5;
        
        /// <summary>
        /// Radio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Radio;
        
        /// <summary>
        /// RadioCheck1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck1;
        
        /// <summary>
        /// RadioCheck2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck2;
        
        /// <summary>
        /// RadioCheck3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck3;
        
        /// <summary>
        /// RadioCheck4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck4;
        
        /// <summary>
        /// Widget6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget6;
        
        /// <summary>
        /// Checkbox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Checkbox;
        
        /// <summary>
        /// RadioCheck5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck5;
        
        /// <summary>
        /// RadioCheck6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck6;
        
        /// <summary>
        /// RadioCheck7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck7;
        
        /// <summary>
        /// RadioCheck8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck8;
        
        /// <summary>
        /// Widget13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget13;
        
        /// <summary>
        /// overlay_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.overlay overlay_1;
        
        /// <summary>
        /// Widget7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget7;
        
        /// <summary>
        /// Input1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Input1;
        
        /// <summary>
        /// Widget8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget8;
        
        /// <summary>
        /// Input2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Input2;
        
        /// <summary>
        /// Widget9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget9;
        
        /// <summary>
        /// Input3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Input3;
        
        /// <summary>
        /// Widget10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget10;
        
        /// <summary>
        /// Input4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Input4;
        
        /// <summary>
        /// Widget11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget11;
        
        /// <summary>
        /// Input5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Input5;
        
        /// <summary>
        /// RadioCheck9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck9;
        
        /// <summary>
        /// RadioCheck10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck10;
        
        /// <summary>
        /// RadioCheck11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck11;
        
        /// <summary>
        /// RadioCheck12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck12;
        
        /// <summary>
        /// Widget12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.Widget Widget12;
        
        /// <summary>
        /// Input6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputFields Input6;
        
        /// <summary>
        /// RadioCheck13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck13;
        
        /// <summary>
        /// RadioCheck14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck14;
        
        /// <summary>
        /// RadioCheck15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck15;
        
        /// <summary>
        /// RadioCheck16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.InputRadioCheck RadioCheck16;
        
        /// <summary>
        /// overlay2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Domotica_ASP.overlay overlay2;
    }
}
